### ISSUE TITLE
new bug for kaptan

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/kaptan#13]
mus@pisi_linux2: ~ $ kaptan --verbose --debug
QLayout: Attempting to add QLayout "" to WelcomeWidget "", which already has a layout
QLayout: Attempting to add QLayout "" to MenuWidget "", which already has a layout
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/kaptan5/kaptan.py", line 79, in optionsAccepted
    self.page(2).execute()
  File "/usr/lib/python3.6/site-packages/kaptan5/libkaptan/ui_theme.py", line 199, in execute
    if self.desktopType != desktopView[1]:
TypeError: 'NoneType' object is not subscriptable
İptal edildi
mus@pisi_linux2:

**Comment by ghost** [comment]
See my PR: #14 
Also, wallpaper setting must be added to ~/.config/plasma-org.kde.plasma.desktop-appletsrc file.
