### ISSUE TITLE
wallpaper değiştirilemiyor

### ISSUE THREAD

**Issue by suvari** [PisiLinuxNew/kaptan#17]
suvari@pisi_linux: ~ $ kaptan
QLayout: Attempting to add QLayout "" to WelcomeWidget "", which already has a layout
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4538
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4588
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4554
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4572
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-color.svg:700:6: Could not resolve property: #linearGradient4548
QLayout: Attempting to add QLayout "" to MenuWidget "", which already has a layout
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4538
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4588
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4554
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4572
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4538
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4588
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4554
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4572
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4532
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4582
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4566
qt.svg: /usr/share/icons/maia/apps/scalable/preferences-desktop-wallpaper.svg:1814:6: Could not resolve property: #linearGradient4548
Warning: Only changing the first 3 of 20 buttons.
/usr/share/color-schemes/Breeze.colors
ColorEffects:Disabled/Color ['56', '56', '56']
ColorEffects:Disabled/ColorAmount 0
ColorEffects:Disabled/ColorEffect 0
ColorEffects:Disabled/ContrastAmount 0.65
ColorEffects:Disabled/ContrastEffect 1
ColorEffects:Disabled/IntensityAmount 0.1
ColorEffects:Disabled/IntensityEffect 2
ColorEffects:Inactive/ChangeSelectionColor true
ColorEffects:Inactive/Color ['112', '111', '110']
ColorEffects:Inactive/ColorAmount 0.025
ColorEffects:Inactive/ColorEffect 2
ColorEffects:Inactive/ContrastAmount 0.1
ColorEffects:Inactive/ContrastEffect 2
ColorEffects:Inactive/Enable false
ColorEffects:Inactive/IntensityAmount 0
ColorEffects:Inactive/IntensityEffect 0
ColorScheme Breeze
Colors:Button/BackgroundAlternate ['189', '195', '199']
Colors:Button/BackgroundNormal ['239', '240', '241']
Colors:Button/DecorationFocus ['61', '174', '233']
Colors:Button/DecorationHover ['147', '206', '233']
Colors:Button/ForegroundActive ['61', '174', '233']
Colors:Button/ForegroundInactive ['127', '140', '141']
Colors:Button/ForegroundLink ['41', '128', '185']
Colors:Button/ForegroundNegative ['218', '68', '83']
Colors:Button/ForegroundNeutral ['246', '116', '0']
Colors:Button/ForegroundNormal ['35', '38', '39']
Colors:Button/ForegroundPositive ['39', '174', '96']
Colors:Button/ForegroundVisited ['127', '140', '141']
Colors:Complementary/BackgroundAlternate ['59', '64', '69']
Colors:Complementary/BackgroundNormal ['49', '54', '59']
Colors:Complementary/DecorationFocus ['30', '146', '255']
Colors:Complementary/DecorationHover ['61', '174', '230']
Colors:Complementary/ForegroundActive ['147', '206', '233']
Colors:Complementary/ForegroundInactive ['175', '176', '179']
Colors:Complementary/ForegroundLink ['61', '174', '230']
Colors:Complementary/ForegroundNegative ['231', '76', '60']
Colors:Complementary/ForegroundNeutral ['253', '188', '75']
Colors:Complementary/ForegroundNormal ['239', '240', '241']
Colors:Complementary/ForegroundPositive ['46', '204', '113']
Colors:Complementary/ForegroundVisited ['61', '174', '230']
Colors:Selection/BackgroundAlternate ['29', '153', '243']
Colors:Selection/BackgroundNormal ['61', '174', '233']
Colors:Selection/DecorationFocus ['61', '174', '233']
Colors:Selection/DecorationHover ['147', '206', '233']
Colors:Selection/ForegroundActive ['252', '252', '252']
Colors:Selection/ForegroundInactive ['239', '240', '241']
Colors:Selection/ForegroundLink ['253', '188', '75']
Colors:Selection/ForegroundNegative ['218', '68', '83']
Colors:Selection/ForegroundNeutral ['246', '116', '0']
Colors:Selection/ForegroundNormal ['252', '252', '252']
Colors:Selection/ForegroundPositive ['39', '174', '96']
Colors:Selection/ForegroundVisited ['189', '195', '199']
Colors:Tooltip/BackgroundAlternate ['77', '77', '77']
Colors:Tooltip/BackgroundNormal ['35', '38', '39']
Colors:Tooltip/DecorationFocus ['61', '174', '233']
Colors:Tooltip/DecorationHover ['147', '206', '233']
Colors:Tooltip/ForegroundActive ['61', '174', '233']
Colors:Tooltip/ForegroundInactive ['189', '195', '199']
Colors:Tooltip/ForegroundLink ['41', '128', '185']
Colors:Tooltip/ForegroundNegative ['218', '68', '83']
Colors:Tooltip/ForegroundNeutral ['246', '116', '0']
Colors:Tooltip/ForegroundNormal ['252', '252', '252']
Colors:Tooltip/ForegroundPositive ['39', '174', '96']
Colors:Tooltip/ForegroundVisited ['127', '140', '141']
Colors:View/BackgroundAlternate ['239', '240', '241']
Colors:View/BackgroundNormal ['252', '252', '252']
Colors:View/DecorationFocus ['61', '174', '233']
Colors:View/DecorationHover ['147', '206', '233']
Colors:View/ForegroundActive ['61', '174', '233']
Colors:View/ForegroundInactive ['127', '140', '141']
Colors:View/ForegroundLink ['41', '128', '185']
Colors:View/ForegroundNegative ['218', '68', '83']
Colors:View/ForegroundNeutral ['246', '116', '0']
Colors:View/ForegroundNormal ['35', '38', '39']
Colors:View/ForegroundPositive ['39', '174', '96']
Colors:View/ForegroundVisited ['127', '140', '141']
Colors:Window/BackgroundAlternate ['189', '195', '199']
Colors:Window/BackgroundNormal ['239', '240', '241']
Colors:Window/DecorationFocus ['61', '174', '233']
Colors:Window/DecorationHover ['147', '206', '233']
Colors:Window/ForegroundActive ['61', '174', '233']
Colors:Window/ForegroundInactive ['127', '140', '141']
Colors:Window/ForegroundLink ['41', '128', '185']
Colors:Window/ForegroundNegative ['218', '68', '83']
Colors:Window/ForegroundNeutral ['246', '116', '0']
Colors:Window/ForegroundNormal ['35', '38', '39']
Colors:Window/ForegroundPositive ['39', '174', '96']
Colors:Window/ForegroundVisited ['127', '140', '141']
KDE/contrast 4
Name Breeze
Name[ar] ÙØ³ÙÙ
Name[az] Breeze
Name[bs] Breeze
Name[ca@valencia] Brisa
Name[ca] Brisa
Name[cs] Breeze
Name[da] Breeze
Name[de] Breeze
Name[el] Breeze
Name[en_GB] Breeze
Name[es] Brisa
Name[et] Breeze
Name[eu] Breeze
Name[fi] Breeze
Name[fr] Brise
Name[gl] Breeze
Name[he] Breeze
Name[hu] Breeze
Name[ia] Brisa
Name[id] Breeze
Name[it] Brezza
Name[ko] Breeze
Name[lt] Breeze
Name[nb] Breeze
Name[nds] Breeze
Name[nl] Breeze
Name[nn] Breeze
Name[pa] à¨¬à¨°à©à©
ame[pl] Bryza
Name[pt] Brisa
Name[pt_BR] Breeze
Name[ro] BrizÄ
Name[ru] Breeze
Name[sk] VÃ¡nok
Name[sl] Sapica
Name[sr@ijekavian] ÐÐ¾Ð²ÐµÑÐ°ÑÐ°Ñ
Name[sr@ijekavianlatin] Povetarac
Name[sr@latin] Povetarac
Name[sr] ÐÐ¾Ð²ÐµÑÐ°ÑÐ°Ñ
Name[sv] Breeze
Name[tg] ÐÐ°ÑÐ¸Ð¼
Name[tr] Esinti
Name[uk] Breeze
Name[x-test] xxBreezexx
Name[zh_CN] Breeze å¾®é£
Name[zh_TW] Breeze
WM/activeBackground ['71', '80', '87']
WM/activeBlend ['252', '252', '252']
WM/activeForeground ['252', '252', '252']
WM/inactiveBackground ['239', '240', '241']
WM/inactiveBlend ['75', '71', '67']
WM/inactiveForeground ['189', '195', '199']
shadeSortColumn true
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/kaptan/kaptan.py", line 75, in optionsAccepted
    self.page(2).execute()
  File "/usr/lib/python3.8/site-packages/kaptan/libkaptan/ui_theme.py", line 197, in execute
    if self.desktopType != desktopView[1]:
TypeError: 'NoneType' object is not subscriptable
İptal edildi
suvari@pisi_linux2: ~ $ kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5127:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5129:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5131:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5135:47: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5137:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5145:48: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5149:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5151:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5155:45: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: /usr/share/X11/locale/en_US.UTF-8/Compose:5158:46: this compose sequence is a duplicate of another; skipping line
kwin_xkbcommon: XKB: Couldn't process include statement for 'tr(\0)'
kwin_xkbcommon: XKB: Abandoning symbols file "(unnamed)"
kwin_xkbcommon: XKB: Failed to compile xkb_symbols
kwin_xkbcommon: XKB: Failed to compile keymap
kwin_core: XCB error: 147 (BadOutput), sequence: 543, resource id: 1095784773, major code: 140 (RANDR), minor code: 9 (GetOutputInfo)
OpenGL vendor string:                   Intel Open Source Technology Center
OpenGL renderer string:                 Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL version string:                  3.0 Mesa 20.3.5
OpenGL shading language version string: 1.30
Driver:                                 Intel
GPU class:                              Unknown
OpenGL version:                         3.0
GLSL version:                           1.30
Mesa version:                           20.3.5
X server version:                       1.20.10
Linux kernel version:                   5.10.5
Requires strict binding:                yes
GLSL shaders:                           yes
Texture NPOT support:                   yes
Virtual Machine:                        no
kwin_core: XCB error: 10 (BadAccess), sequence: 2414, resource id: 377, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)

**Comment by suvari** [comment]
fixed
